services: 
  db:
    image: mariadb:lts
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./backups:/backups
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  web:
    build: phpserver
    restart: always
    depends_on: 
      db: 
        condition: service_healthy
        restart: true
    ports: 
      - $WWW_PORT:80
    links: 
      - db:db
    volumes:
      - './www:/var/www/html'
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    depends_on:
      db: 
        condition: service_healthy
        restart: true
    ports: 
      - $PHPMYADMIN_PORT:80
    links:
      - db:mysql_db_server

volumes:
  db_data: {}

